#!/usr/bin/env python3
"""Audit a DOCX or the skill bundle for GJB438C template compliance.

Key facts encoded here (measured from the bundled template):
- Headings are auto-numbered by the template multilevel list; heading text
  must not start with a typed number prefix (double-numbering).
- Table header cells use 145表头, table body cells use 145表正文.
- Figure placeholder paragraphs use 145图样式; captions use Caption with
  chapter-based numbering (图 X-Y / 表X-Y).
"""

from __future__ import annotations

import argparse
import json
import re
import zipfile
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

import yaml
from docx import Document


REQUIRED_STYLES = {
    "Heading 1",
    "Heading 2",
    "Heading 3",
    "Heading 4",
    "Heading 5",
    "145正文",
    "145图样式",
    "145表头",
    "145表正文",
    "Caption",
    "311-目录标题",
    "toc 1",
    "toc 2",
    "toc 3",
    "编号密级",
    "文件名称",
    "单位名称",
}

# Defined in the template style sheet but never used in the document body.
FORBIDDEN_CONTENT_STYLES = {"DB表头", "DB表正文"}

TABLE_HEADER_STYLE = "145表头"
TABLE_BODY_STYLE = "145表正文"
FIGURE_STYLE = "145图样式"

REQUIRED_H1 = [
    "概述",
    "使用与技术指标要求",
    "总体架构",
    "分系统设计",
    "系统集成设计",
    "关键技术分析",
    "效能分析",
    "工程组织管理",
    "初步工作计划",
]

GJB_DOCUMENT_TYPES = {
    "SDP": ("软件开发计划", "A"),
    "SIP": ("软件安装计划", "B"),
    "STrP": ("软件移交计划", "C"),
    "STP": ("软件测试计划", "D"),
    "OCD": ("运行方案说明", "E"),
    "SSS": ("系统/子系统规格说明", "F"),
    "IRS": ("接口需求规格说明", "G"),
    "SSDD": ("系统/子系统设计说明", "H"),
    "IDD": ("接口设计说明", "I"),
    "SRS": ("软件需求规格说明", "J"),
    "SDD": ("软件设计说明", "K"),
    "DBDD": ("数据库设计说明", "L"),
    "STD": ("软件测试说明", "M"),
    "STR": ("软件测试报告", "N"),
    "SPS": ("软件产品规格说明", "O"),
    "SVD": ("软件版本说明", "P"),
    "SUM": ("软件用户手册", "Q"),
    "CPM": ("计算机编程手册", "R"),
    "FSM": ("固件保障手册", "S"),
    "SDSR": ("软件研制总结报告", "T"),
}

STRICT_H2 = {
    "概述": {"任务依据", "编制目的", "指导原则", "建设目标", "主要工作", "与其他项目关系", "名词术语", "缩略语"},
    "使用与技术指标要求": {"使用要求", "技术指标要求"},
    "总体架构": {"体系架构设计", "逻辑架构设计", "系统架构设计", "功能架构设计", "数据架构设计", "部署架构设计", "数据交换设计", "关键性能指标设计", "组织运用模式", "技术体制"},
    "工程组织管理": {"组织机构", "考核验收", "安全保密"},
}

LEGACY_TERMS = ["ZBZQ", "XX数据中台", "联合XX数据资源体系", "XX数据融合治理"]
FORBIDDEN_LOCAL_PATH_TOKENS = [
    "/" + "Users" + "/",
    "/" + "home" + "/",
    "C:" + "\\" + "Users" + "\\",
]

TYPED_NUMBER_RE = re.compile(r"^\d+(?:\.\d+)*[\s　]")
CAPTION_NUMBER_RE = re.compile(r"^(图|表)\s*\d+-\d+")
HEADING_STYLES = {"Heading 1", "Heading 2", "Heading 3", "Heading 4", "Heading 5"}

W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
R_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"
REL_NS = "http://schemas.openxmlformats.org/package/2006/relationships"
XML_NS = {"w": W_NS, "r": R_NS, "rel": REL_NS}
W = f"{{{W_NS}}}"
R = f"{{{R_NS}}}"


def strip_heading_number(text: str) -> str:
    return re.sub(r"^\d+(?:\.\d+)*\s+", "", text).strip()


@dataclass
class AuditResult:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.errors

    def add_error(self, message: str) -> None:
        self.errors.append(message)

    def add_warning(self, message: str) -> None:
        self.warnings.append(message)


TOC_STYLES = {f"toc {level}" for level in range(1, 10)}


def paragraph_texts(document: Document) -> Iterable[str]:
    """Visible content text, excluding TOC field results.

    TOC paragraphs are stale field caches regenerated by Word on open
    (w:updateFields), so legacy-term scans must not flag them.
    """
    for paragraph in document.paragraphs:
        style_name = paragraph.style.name if paragraph.style else ""
        if style_name in TOC_STYLES:
            continue
        text = paragraph.text.strip()
        if text:
            yield text
    for table in document.tables:
        for row in table.rows:
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    text = paragraph.text.strip()
                    if text:
                        yield text


def is_cover_table(table) -> bool:
    """The template cover table uses cover styles in its first row."""
    cover_styles = {"编号密级", "文头字", "文件标识号", "文件名称", "单位名称"}
    for cell in table.rows[0].cells:
        for paragraph in cell.paragraphs:
            style_name = paragraph.style.name if paragraph.style else ""
            if style_name in cover_styles:
                return True
    return False


def xml_attr(element: ET.Element | None, namespace: str, local_name: str) -> str | None:
    if element is None:
        return None
    return element.get(f"{{{namespace}}}{local_name}")


def read_package_xml(package: zipfile.ZipFile, name: str, result: AuditResult) -> ET.Element | None:
    try:
        return ET.fromstring(package.read(name))
    except KeyError:
        result.add_error(f"DOCX package is missing required XML part: {name}")
    except ET.ParseError as exc:
        result.add_error(f"DOCX XML part is not parseable: {name}: {exc}")
    return None


def package_xml_text(root: ET.Element, xpath: str) -> str:
    return " ".join((node.text or "") for node in root.findall(xpath, XML_NS))


def document_has_toc_field(path: Path, result: AuditResult) -> bool:
    with zipfile.ZipFile(path) as package:
        document_root = read_package_xml(package, "word/document.xml", result)
        if document_root is None:
            return False
        instr_text = package_xml_text(document_root, ".//w:instrText")
        fld_simple_instr = " ".join(
            xml_attr(node, W_NS, "instr") or ""
            for node in document_root.findall(".//w:fldSimple", XML_NS)
        )
        return "TOC" in (instr_text + " " + fld_simple_instr).upper()


def relationship_targets(package: zipfile.ZipFile, result: AuditResult) -> dict[str, str]:
    root = read_package_xml(package, "word/_rels/document.xml.rels", result)
    if root is None:
        return {}
    targets: dict[str, str] = {}
    for rel in root.findall("rel:Relationship", XML_NS):
        rel_id = rel.get("Id")
        target = rel.get("Target")
        if rel_id and target:
            targets[rel_id] = target
    return targets


def footer_part_name(target: str | None) -> str | None:
    if not target:
        return None
    return target if target.startswith("word/") else f"word/{target}"


def footer_has_page_field(package: zipfile.ZipFile, part_name: str | None, result: AuditResult) -> bool:
    if not part_name:
        return False
    root = read_package_xml(package, part_name, result)
    if root is None:
        return False
    instr_text = " ".join((node.text or "") for node in root.findall(".//w:instrText", XML_NS))
    return "PAGE" in instr_text.upper()


def footer_has_centered_page_field(package: zipfile.ZipFile, part_name: str | None, result: AuditResult) -> bool:
    if not part_name:
        return False
    root = read_package_xml(package, part_name, result)
    if root is None:
        return False
    for paragraph in root.findall(".//w:p", XML_NS):
        instr_text = " ".join((node.text or "") for node in paragraph.findall(".//w:instrText", XML_NS))
        if "PAGE" not in instr_text.upper():
            continue
        jc = paragraph.find("./w:pPr/w:jc", XML_NS)
        if xml_attr(jc, W_NS, "val") == "center":
            return True
    return False


def footer_has_dash_page_dash(package: zipfile.ZipFile, part_name: str | None, result: AuditResult) -> bool:
    if not part_name:
        return False
    root = read_package_xml(package, part_name, result)
    if root is None:
        return False
    has_page = footer_has_page_field(package, part_name, result)
    text_runs = [node.text or "" for node in root.findall(".//w:t", XML_NS)]
    dash_count = sum(text.count("—") for text in text_runs)
    return has_page and dash_count >= 2


def audit_page_numbering(path: Path, result: AuditResult) -> None:
    """Audit the template-owned page-number and footer structure.

    The check intentionally relies on Word field instructions and section
    relationships, not stale field-result text such as "II" or "22".
    """
    with zipfile.ZipFile(path) as package:
        document_root = read_package_xml(package, "word/document.xml", result)
        if document_root is None:
            return
        relationships = relationship_targets(package, result)
        section_properties = document_root.findall(".//w:sectPr", XML_NS)
        if len(section_properties) != 2:
            result.add_error(f"Expected exactly 2 section properties for front matter and body, got {len(section_properties)}")
            return

        for index, section in enumerate(section_properties, start=1):
            page_size = section.find("w:pgSz", XML_NS)
            width = xml_attr(page_size, W_NS, "w")
            height = xml_attr(page_size, W_NS, "h")
            if width != "11906" or height != "16838":
                result.add_error(f"Section {index} page size is not A4 template size 11906 x 16838 twips: {width} x {height}")

        front_section, body_section = section_properties
        front_page_numbering = front_section.find("w:pgNumType", XML_NS)
        if xml_attr(front_page_numbering, W_NS, "fmt") != "upperRoman" or xml_attr(front_page_numbering, W_NS, "start") != "1":
            result.add_error("Front-matter section must use upperRoman page numbers starting at 1")
        if front_section.find("w:titlePg", XML_NS) is None:
            result.add_error("Front-matter section must preserve titlePg so the cover can omit visible page number")

        front_footers = {
            xml_attr(ref, W_NS, "type"): footer_part_name(relationships.get(xml_attr(ref, R_NS, "id")))
            for ref in front_section.findall("w:footerReference", XML_NS)
        }
        front_default_footer = front_footers.get("default")
        if not front_default_footer:
            result.add_error("Front-matter section must preserve a default footer reference for roman page numbers")
        elif not footer_has_centered_page_field(package, front_default_footer, result):
            result.add_error("Front-matter default footer must contain a centered native Word PAGE field")

        body_headers = body_section.findall("w:headerReference", XML_NS)
        body_footers = body_section.findall("w:footerReference", XML_NS)
        if not body_headers:
            result.add_error("Body section must preserve template header references")
        if not body_footers:
            result.add_error("Body section must preserve template footer references")

        body_footer_parts = [
            footer_part_name(relationships.get(xml_attr(ref, R_NS, "id")))
            for ref in body_footers
        ]
        body_page_footers = [
            part_name for part_name in body_footer_parts
            if footer_has_page_field(package, part_name, result)
        ]
        if not body_page_footers:
            result.add_error("Body section footer must contain a native Word PAGE field")
        elif not any(footer_has_dash_page_dash(package, part_name, result) for part_name in body_page_footers):
            result.add_error("Body section page footer must preserve the template dash-PAGE-dash visual pattern")

        settings_root = read_package_xml(package, "word/settings.xml", result)
        if settings_root is not None:
            update_fields = settings_root.find("w:updateFields", XML_NS)
            if update_fields is None or xml_attr(update_fields, W_NS, "val") not in {None, "true", "1", "on"}:
                result.add_warning("word/settings.xml does not request field refresh with w:updateFields=true")


def audit_gjb_composition(path: Path, document: Document, result: AuditResult, strict_gjb_composition: bool) -> None:
    def add_composition_issue(message: str) -> None:
        if strict_gjb_composition:
            result.add_error(message)
        else:
            result.add_warning(message)

    if not document.tables or not any(is_cover_table(table) for table in document.tables):
        result.add_error("Document must preserve a cover table using the template cover styles")

    if not document_has_toc_field(path, result):
        result.add_error("Document must preserve a real Word TOC field instead of static TOC text")

    full_visible_text = "\n".join(paragraph_texts(document))
    if not any(token in full_visible_text for token in ["修改页", "修改记录", "修改历史", "修订记录", "变更记录"]):
        add_composition_issue("GJB 438C composition expects a modification page/history; none was found")

    heading1_count = sum(
        1 for paragraph in document.paragraphs
        if paragraph.text.strip() and paragraph.style and paragraph.style.name == "Heading 1"
    )
    if heading1_count == 0:
        result.add_error("Document body must contain at least one Heading 1 body chapter/clause")


def audit_docx(path: Path, strict_secondary: bool, strict_tables: bool, strict_overall: bool = False, strict_gjb_composition: bool = False) -> AuditResult:
    result = AuditResult()
    if not path.exists():
        result.add_error(f"DOCX does not exist: {path}")
        return result
    if not zipfile.is_zipfile(path):
        result.add_error(f"DOCX is not a valid zip package: {path}")
        return result
    audit_page_numbering(path, result)

    document = Document(path)
    styles = {style.name for style in document.styles}
    missing_styles = sorted(REQUIRED_STYLES - styles)
    if missing_styles:
        result.add_error(f"Missing required styles: {', '.join(missing_styles)}")

    audit_gjb_composition(path, document, result, strict_gjb_composition)

    full_text = "\n".join(paragraph_texts(document))
    for term in LEGACY_TERMS:
        if term in full_text:
            result.add_error(f"Legacy template term remains in document: {term}")
    for token in FORBIDDEN_LOCAL_PATH_TOKENS:
        if token in full_text:
            result.add_error(f"Local environment path remains in document: {token}")

    h1_seen: list[str] = []
    current_primary: str | None = None
    overall_mode = strict_overall or strict_secondary
    for paragraph in document.paragraphs:
        text = paragraph.text.strip()
        if not text:
            continue
        style_name = paragraph.style.name if paragraph.style else ""
        if style_name in {"toc 1", "toc 2", "toc 3"}:
            continue

        if style_name in HEADING_STYLES:
            # Double-numbering guard: the multilevel list renders numbers.
            if TYPED_NUMBER_RE.match(text):
                result.add_error(
                    f"Heading text starts with a typed number (auto-numbering makes it double): {text[:40]}"
                )
            normalized = strip_heading_number(text)
            if style_name == "Heading 1":
                h1_seen.append(normalized)
                if normalized in REQUIRED_H1:
                    current_primary = normalized
                else:
                    current_primary = None
                    if overall_mode:
                        result.add_error(f"First-level heading is outside template framework: {text}")
            elif style_name == "Heading 2" and strict_secondary and current_primary in STRICT_H2:
                allowed = STRICT_H2[current_primary]
                if normalized not in allowed:
                    result.add_error(f"Second-level heading is outside template framework: {text}")
            continue

        if style_name in FORBIDDEN_CONTENT_STYLES:
            result.add_error(f"Paragraph uses forbidden style {style_name!r}: {text[:40]}")

        if style_name == "Normal":
            result.add_error(f"Body paragraph uses 'Normal' instead of '145正文': {text[:40]}")

        if style_name == "Caption" and not CAPTION_NUMBER_RE.match(text):
            result.add_warning(
                f"Caption does not follow chapter-based numbering 图 X-Y / 表X-Y: {text[:40]}"
            )

    if overall_mode and h1_seen != REQUIRED_H1:
        result.add_error(f"First-level chapter sequence mismatch. Expected {REQUIRED_H1}, got {h1_seen}")

    for table_index, table in enumerate(document.tables, start=1):
        if is_cover_table(table):
            continue
        for row_index, row in enumerate(table.rows):
            expected = TABLE_HEADER_STYLE if row_index == 0 else TABLE_BODY_STYLE
            for cell in row.cells:
                for paragraph in cell.paragraphs:
                    text = paragraph.text.strip()
                    if not text:
                        continue
                    style_name = paragraph.style.name if paragraph.style else ""
                    if style_name != expected:
                        message = f"Table {table_index} row {row_index + 1} cell paragraph uses {style_name!r}, expected {expected!r}: {text[:40]}"
                        if strict_tables:
                            result.add_error(message)
                        else:
                            result.add_warning(message)

    return result


def parse_frontmatter(skill_md: Path) -> dict[str, str]:
    text = skill_md.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise ValueError("SKILL.md must start with YAML frontmatter")
    end = text.find("\n---", 4)
    if end < 0:
        raise ValueError("SKILL.md frontmatter is not closed")
    metadata = yaml.safe_load(text[4:end]) or {}
    if not isinstance(metadata, dict):
        raise ValueError("SKILL.md frontmatter must be a mapping")
    return metadata


def iter_text_files(root: Path) -> Iterable[Path]:
    for path in root.rglob("*"):
        if path.is_file() and path.suffix.lower() in {".md", ".py", ".yml", ".yaml", ".toml", ".txt"}:
            yield path


def validate_skill(skill_dir: Path) -> AuditResult:
    skill_dir = skill_dir.resolve()
    result = AuditResult()
    required_paths = [
        skill_dir / "SKILL.md",
        skill_dir / "agents" / "openai.yaml",
        skill_dir / "assets" / "1-2总体技术方案-模板参考.docx",
        skill_dir / "references" / "template-structure.md",
        skill_dir / "references" / "gjb438c-2021-requirements.md",
        skill_dir / "references" / "format-lock.md",
        skill_dir / "references" / "writing-prompts.md",
        skill_dir / "scripts" / "apply_gjb438c_template.py",
        skill_dir / "scripts" / "audit_gjb438c_docx.py",
    ]
    for path in required_paths:
        if not path.exists():
            result.add_error(f"Missing required skill file: {path}")

    if (skill_dir / "README.md").exists():
        result.add_error("Skill body must not contain README.md; keep repository docs at repo root.")

    skill_md = skill_dir / "SKILL.md"
    if skill_md.exists():
        try:
            metadata = parse_frontmatter(skill_md)
            if metadata.get("name") != skill_dir.name:
                result.add_error(f"Skill name {metadata.get('name')!r} does not match folder name {skill_dir.name!r}")
            if not metadata.get("description"):
                result.add_error("SKILL.md description is required")
        except Exception as exc:
            result.add_error(f"Invalid SKILL.md frontmatter: {exc}")

    template = skill_dir / "assets" / "1-2总体技术方案-模板参考.docx"
    if template.exists() and not zipfile.is_zipfile(template):
        result.add_error(f"Template asset is not a valid DOCX package: {template}")

    for path in iter_text_files(skill_dir):
        text = path.read_text(encoding="utf-8", errors="ignore")
        for token in FORBIDDEN_LOCAL_PATH_TOKENS:
            if token in text:
                result.add_error(f"Local environment path appears in {path}: {token}")

    return result


def print_result(result: AuditResult, as_json: bool) -> None:
    if as_json:
        print(json.dumps({"ok": result.ok, "errors": result.errors, "warnings": result.warnings}, ensure_ascii=False, indent=2))
        return
    if result.errors:
        print("ERRORS:")
        for item in result.errors:
            print(f"- {item}")
    if result.warnings:
        print("WARNINGS:")
        for item in result.warnings:
            print(f"- {item}")
    if result.ok:
        print("OK")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("docx", nargs="?", type=Path, help="DOCX file to audit.")
    parser.add_argument("--skill-dir", type=Path, help="Skill directory to validate.")
    parser.add_argument("--validate-skill", action="store_true", help="Validate the skill bundle structure.")
    parser.add_argument("--strict-secondary", action="store_true", help="Require fixed second-level headings where the template defines them.")
    parser.add_argument("--strict-overall", action="store_true", help="Require the overall technical solution's fixed nine first-level chapters.")
    parser.add_argument("--strict-gjb-composition", action="store_true", help="Treat missing GJB composition elements such as modification history as errors.")
    parser.add_argument("--strict-tables", action="store_true", help="Treat table style mismatches as errors.")
    parser.add_argument("--json", action="store_true", help="Print machine-readable audit output.")
    return parser.parse_args()


def merge_results(results: list[AuditResult]) -> AuditResult:
    merged = AuditResult()
    for result in results:
        merged.errors.extend(result.errors)
        merged.warnings.extend(result.warnings)
    return merged


def main() -> int:
    args = parse_args()
    results: list[AuditResult] = []
    if args.validate_skill:
        if not args.skill_dir:
            raise SystemExit("--validate-skill requires --skill-dir")
        results.append(validate_skill(args.skill_dir))
    if args.docx:
        results.append(
            audit_docx(
                args.docx,
                args.strict_secondary,
                args.strict_tables,
                strict_overall=args.strict_overall,
                strict_gjb_composition=args.strict_gjb_composition,
            )
        )
    if not results:
        raise SystemExit("Provide a DOCX path and/or --validate-skill --skill-dir")
    result = merge_results(results)
    print_result(result, args.json)
    return 0 if result.ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
